version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iridiumsystems_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www          
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: iridiumsystems_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: iridiumsystems_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iridium_systems        # changed to your project name
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
   
    ports:
      - "3307:3306"   # 
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  db_data:
